# Generated by Django 4.2.2 on 2023-07-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investisment', '0002_alter_investisment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investisment',
            old_name='new_invest',
            new_name='invest',
        ),
    ]
