# Generated by Django 4.2.2 on 2023-07-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain', models.CharField(choices=[('Ethereum', 'Ethereum'), ('Bsc', 'Bsc'), ('Bitcoin', 'Bitcoin'), ('Avalanche', 'Avalanche'), ('Polkadot', 'Polkadot'), ('Oasis', 'Oasis'), ('Galeon', 'Galeon'), ('Harmony', 'Harmony'), ('Autres', 'Autres')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='BuyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
