# Generated by Django 4.2.2 on 2023-07-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blockchain',
        ),
        migrations.AddField(
            model_name='buyasset',
            name='blockchain',
            field=models.CharField(choices=[('Ethereum', 'Ethereum'), ('Bsc', 'Bsc'), ('Bitcoin', 'Bitcoin'), ('Avalanche', 'Avalanche'), ('Polkadot', 'Polkadot'), ('Oasis', 'Oasis'), ('Galeon', 'Galeon'), ('Harmony', 'Harmony'), ('Autres', 'Autres')], default='', max_length=25),
            preserve_default=False,
        ),
    ]
