# Generated by Django 4.2.2 on 2023-07-09 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_invest', models.FloatField()),
                ('date', models.DateField(default=datetime.datetime(2023, 7, 9, 20, 29, 48, 705527, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AddField(
            model_name='buyasset',
            name='blockchain',
            field=models.CharField(choices=[('Ethereum', 'Ethereum'), ('Bsc', 'Bsc'), ('Bitcoin', 'Bitcoin'), ('Avalanche', 'Avalanche'), ('Polkadot', 'Polkadot'), ('Oasis', 'Oasis'), ('Galeon', 'Galeon'), ('Harmony', 'Harmony'), ('Autres', 'Autres')], default='', max_length=25),
            preserve_default=False,
        ),
    ]
