# Generated by Django 4.2.2 on 2023-07-09 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_investisment_buyasset_blockchain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investisment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 20, 36, 20, 649896, tzinfo=datetime.timezone.utc)),
        ),
    ]
