# Generated by Django 4.2.2 on 2023-07-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_investisment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investisment',
            name='date',
            field=models.DateField(),
        ),
    ]
