# Generated by Django 4.2.2 on 2023-07-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_investisment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain', models.CharField(choices=[('Ethereum', 'Ethereum'), ('Bsc', 'Bsc'), ('Bitcoin', 'Bitcoin'), ('Avalanche', 'Avalanche'), ('Polkadot', 'Polkadot'), ('Oasis', 'Oasis'), ('Galeon', 'Galeon'), ('Harmony', 'Harmony'), ('Autres', 'Autres')], max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='buyasset',
            name='blockchain',
        ),
    ]
