# Generated by Django 4.2.2 on 2023-07-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_blockchain_remove_buyasset_blockchain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investisment',
            name='date',
            field=models.DateField(default='DD/MM/YY', error_messages={'required': 'Please enter your name'}),
        ),
        migrations.AlterField(
            model_name='investisment',
            name='new_invest',
            field=models.FloatField(default=0),
        ),
    ]
