# Generated by Django 4.2.2 on 2023-07-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_investisment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investisment',
            name='date',
            field=models.DateField(default='DD/MM/YY', error_messages='test'),
        ),
    ]
