# Generated by Django 4.2.2 on 2023-07-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_investisment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investisment',
            name='date',
            field=models.DateField(default='DD/MM/YY', error_messages={'unique': 'The Geeks Field you entered is not unique.'}),
        ),
    ]
