# Generated by Django 4.2.2 on 2023-07-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_rename_amount_buyasset_asset_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyasset',
            old_name='asset_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='buyasset',
            old_name='asset_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='buyasset',
            old_name='asset_asset_price',
            new_name='price',
        ),
    ]
